### ISSUE TITLE
Lots of errors about narrowing conversions while compiling cld2-sys

### ISSUE THREAD

**Issue by runiq** [emk/rust-cld2#2]
I was trying to install the `substudy` package but could not, due to `cld2-sys` failing to compile. There were lots of errors about failed narrowing conversions (see attached build log file).

I am trying to compile on an up-to-date Arch Linux x86_64 system (with Japanese locale in case that makes any difference). I have also tried to compile the 0.4.1-pre.1 version of `substudy`, with the same results. (The attached file is from the release version, however.) I am not using multirust, just the version of Rust that is in the Arch Linux repositories (1.13.0, cargo version is 0.13.0).

[substudy-install.log.txt](https://github.com/emk/rust-cld2/files/590272/substudy-install.log.txt)

**Comment by emk** [comment]
Thank you for the bug report!

Unfortunately, this appears to be a breaking change in the C++ standard, and it affects the (very large) data tables in the cld2 source code. This may not be especially easy to fix. We might try updating to the latest cld2 release?

**Comment by runiq** [comment]
Take your time, no worries! :)

The bug you describe—is it the same as the one described in [this](http://stackoverflow.com/q/4434140) question? If so, might it be enough for now if I tell GCC to not use the C++11 standard?

**Comment by emk** [comment]
Yes, I believe that's what's going on. You might be able to change which C++ standard you're using or adjust the warning flags. I'll happily take a PR which does either.

Fixing the underlying tables is hard because it may make the source code bigger, and if our source code gets just a bit bigger, we may not be able to upload releases to crates.io. We already have a tool to strip comments and remove unused files, IIRC.

**Comment by emk** [comment]
Since passing a flag to the compiler doesn't seem to be very portable, here's another alternative from [the cld issue tracker](https://github.com/CLD2Owners/cld2/issues/47). It looks like we can pass an environment variable specifying the C++ version. It think there's a relatively easy way to do this using Cargo.

**Comment by emk** [comment]
The variable we need from that thread is `CPPFLAGS="-std=c++98", with credit to @alc-privacore.

But that's not a regular environment variable, it's really just a different set of compiler flags, so we may need to experiment a bit to figure out if it works for all the different C++ compilers we use. But it's likely to be easier to conditionalize this than the `-Wno-` flag.

**Comment by runiq** [comment]
Sorry, I was already in bed by the time the CI builds errored out.

Yeah, I chose the solution I hoped would have the minimum impact but still fix the issue. I hadn't even thought about different compilers and platforms, because judging from the package name (`gcc`), I thought it would be GCC-only anyways.

I'll look into what the `gcc` package does to abstract away compiler settings tonight, maybe it helps if I change the flag depending on the target triple. I'll keep the comments in #3 from now on. :)

**Comment by runiq** [comment]
Something I just noticed in [a bug report you filed with crates.io](https://github.com/rust-lang/crates.io/issues/40): Shouldn't it be possible now to raise the crate size limit on a per-crate basis, as per [this comment](https://github.com/rust-lang/crates.io/issues/40#issuecomment-157919165)? In other words, is the size limit still a problem?

**Comment by emk** [comment]
Oh, hey, nice. Thank you for finding that!

It would be nice to try to fix this upstream in the `cld2` project itself (it was reported a while back), and then update to the latest cld2.

I'm hoping to release a new `cld2` with your fix this weekend, if all goes well. Ping me if I appear to have forgotten it—I'm juggling both https://github.com/faradayio/cage and an internal Rust project on an very ambitious deadline right now, and I may need a reminder for substudy-related stuff.

**Comment by emk** [comment]
OK, it looks like I'm going to try to handle Rust PRs _this_ weekend, instead. My apologies for the delay!

**Comment by mjal** [comment]
+1, the pull request worked for me. It's sad that the CI failed with rust nighly.

**Comment by emk** [comment]
OK, I'd like to apologize for taking so long to dig out from under my PR backlog. I've just released v1.0.1, which includes this fix and a few other minor modernizations. Thank you for all your help, and my apologies once again for the delay!
